so_core:
    user:
        class: \App\Entity\User
        activation:
            expire: "48 hours"
        recover:
            expire: "4 hours"
    email:
        from:
            name: "SoIngenious"
            email: "no-reply@sowapps.com"
        contact:
            name: "Contact Sowapps"
            email: "contact@sowapps.com"
        online_view:
            expire: "48 hours"
    file:
        store_path: "%kernel.project_dir%/var/store/files"
        public_path: "%kernel.project_dir%/public"
        purposes:
            - article_main
            - widget_image
            - import_language
        sources:
            - fixture
            - http_upload
            - local
        storages:
            - local
    admin:
        auth:
            background:
                - 'bundles/socore/img/login-backgrounds/harley-davidson-bs1eqd6zSiU-unsplash.jpg'
                - 'bundles/socore/img/login-backgrounds/mark-harpur-K2s_YE031CA-unsplash.jpg'
                - 'bundles/socore/img/login-backgrounds/pietro-de-grandi-T7K4aEPoGGk-unsplash.jpg'
    routing:
        route:
            public_default: 'app_index'
