twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ '@SoCore/theme/bootstrap_5.html.twig', '@SoCore/theme/so_core.html.twig' ]
    globals:
        fileService: '@Sowapps\SoCore\Service\FileService'
        language: '@Sowapps\SoCore\Service\LanguageService'
        userService: '@Sowapps\SoCore\Service\AbstractUserService'

when@test:
    twig:
        strict_variables: true
