so_core:
    resource: '@SoCoreBundle/config/routes.yaml'

so_log:
    resource: '@SoLogBundle/config/routes.yaml'

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: '/{_locale}'
    requirements:
        _locale: '[a-zA-Z]{2}|[a-zA-Z]{2}\-[a-zA-Z]{2}'

databaseRouting:
    resource: App\Service\Routing\DatabaseRoutingService::loadRoutes
    type: service
    prefix: '/{_locale}'
    requirements:
        _locale: '[a-zA-Z]{2}|[a-zA-Z]{2}\-[a-zA-Z]{2}'

#fragmentArticles:
#    resource: App\Service\Routing\FragmentArticleRoutingService::loadRoutes
#    type: service
#    prefix: '/{_locale}'
#    requirements:
#        _locale: '[a-zA-Z]{2}|[a-zA-Z]{2}\-[a-zA-Z]{2}'
#
#fragmentPages:
#    resource: App\Service\Routing\FragmentPageRoutingService::loadRoutes
#    type: service
#    prefix: '/{_locale}'
#    requirements:
#        _locale: '[a-zA-Z]{2}|[a-zA-Z]{2}\-[a-zA-Z]{2}'
